name: Frontend Test

on:
  pull_request:
    branches:
      - main
      - "release/v*.*.*"
    paths:
      - "web/**"

jobs:
  eslint-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: yarn
          cache-dependency-path: "web/yarn.lock"
      - run: yarn
        working-directory: web
      - name: Run eslint check
        run: yarn lint
        working-directory: web

  jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: yarn
          cache-dependency-path: "web/yarn.lock"
      - run: yarn
        working-directory: web
      - name: Run jest
        run: yarn test
        working-directory: web

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: yarn
          cache-dependency-path: "web/yarn.lock"
      - run: yarn
        working-directory: web
      - name: Run frontend build
        run: yarn build
        working-directory: web
