name: 'Git Tag Annotation'
description: 'Get the annotation associated with a git tag'
author: 'Eric Cornelissen'

inputs:
  tag:
    description: 'tag of interest (defaults to the GITHUB_REF environment variable)'
    required: false

outputs:
  git-tag-annotation:
    description: 'The git tag annotation'

runs:
  using: 'node12'
  main: 'lib/index.js'

branding:
  icon: 'tag'
  color: 'gray-dark'
